### ISSUE TITLE
What do you think of generational ZGC?

### ISSUE THREAD

**Issue by Niterux** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#12]
I heard it brings great performance improvements over regular ZGC so why isn't it mentioned? It seems to run fine for me (in fact it runs significantly better than g1gc on the client for me) and the next major version of Minecraft requires Java 21 anyways.

**Comment by Mukul1127** [comment]
Okay, I never heard about this, it seems fine so I'll add it soon

**Comment by Mukul1127** [comment]
Seems like ZGC is self-tuning, quickly wrote up a section about it.

**Comment by pog5** [comment]
> Seems like ZGC is self-tuning, quickly wrote up a section about it.
Yeah but how does ZGenerational (generational ZGC) perform compared to the other GCs on the client and serverside? Could you add some benchmarks to the readme if possible? thank you very much!
