### ISSUE TITLE
GraalVM 8 ee?

### ISSUE THREAD

**Issue by Muha0644** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#13]
Where can i download GraalVM EE for java 8? It seems like Oracle removed it from their website, and i can't find it anywhere. Java 17 is downloadable, but not 8 for some reason...

Any clues? Maybe an archive.org link? Or is there no way to run minecraft 1.12.2 using graalvm enterprise edition (I've read that the community edition is barely better than e.g. adoptium) ?

**Comment by Muha0644** [comment]
I see no way of downloading the files without breaking the Oracle terms of service, so I've broken the terms of service...
There is no way they won't ban my account, since i put the company name as "Ligma GmbH" and similar...

Anyways, if anyone else is reading this issue and you don't want to get into trouble with Oracle, i have downloaded the grallvm ee files for java 8 and 11. I will probably upload them somewhere. Just ask in case i forget to update this issue.

**Comment by Mukul1127** [comment]
https://www.oracle.com/downloads/graalvm-downloads.html select GraalVM Enterprise 21

**Comment by Mukul1127** [comment]
Also GraalVM Enterprise 22 has a more updated jdk 11

**Comment by Muha0644** [comment]
Yeah, I downloaded everything. You can't download any of them without an oracle account though...

**Comment by Mukul1127** [comment]
that's not something I can change as I think it's not allowed to re upload
