### ISSUE TITLE
ZGC is not/should not be proactive

### ISSUE THREAD

**Issue by JL2210** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#17]
Proactive ZGC is good for applications with low allocation rate. This is not true for Minecraft, and the flag in question explicitly *disables* Proactive ZGC (since it is enabled by default):

```
-XX:-ZProactive
```

XX options are enabled with `+` and disabled with `-`. See for example Generational ZGC the line below:

```
-XX:+ZGenerational
```

**Comment by Mukul1127** [comment]
First of all, your question is kinda confusing, what do you mean we should change? It kinda seems like your thing got cut off

Also refering to Generational ZGC:
1: Generational ZGC is very new so probably not many people have tested it, especially on minecraft
2: Generational ZGC is only on Java 21 which doesn't work great on old versions
So thats why we are currently recommending Proactive ZGC instead of Generational ZGC

**Comment by Mukul1127** [comment]
> First of all, your question is kinda confusing, what do you think we should change? It kinda seems like your thing got cut off
> 
> Also refering to Generational ZGC: 1: Generational ZGC is very new so probably not many people have tested it, especially on minecraft 2: Generational ZGC is only on Java 21 which doesn't work great on old versions So thats why we are currently recommending Proactive ZGC instead of Generational ZGC

**Comment by JL2210** [comment]
Call it "ZGC" instead of "Proactive ZGC". The flags are correct, the description isn't.

Commit that introduced the error is https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/commit/888cb1530281abbb0cbeca47ce0f540bfc95dc64

I was just using Generational ZGC as an example for how the XX flags work

**Comment by Mukul1127** [comment]
I called it Proactive ZGC so people wouldn't get confused with Generational ZGC

**Comment by Mukul1127** [comment]
Also so you mean that the Proactive ZGC section is actually using Generational ZGC or am I misunderstanding

**Comment by JL2210** [comment]
Well, calling it Proactive ZGC is wrong because that's what the flag is disabling. It's not Generational ZGC either because that's not enabled by default. What's called the "proactive ZGC" section now is non-generational ZGC with proactive collection disabled. I would just change it back to what it was before

Again generational ZGC was just an example and has nothing to do with this

**Comment by Mukul1127** [comment]
Ohhhh ok, so I should change generational ZGC to plus and rename proactive to just ZGC

**Comment by Mukul1127** [comment]
https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/commit/1f2d8ada850e8769a721ea5aac8ed9212277b9c0
