### ISSUE TITLE
G1ConcRSHotCardLimit have been obsoleted on JDK 21

### ISSUE THREAD

**Issue by mateus3c** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#2]
Check: https://www.oracle.com/java/technologies/javase/21all-relnotes.html

On your GraalVM 21 flags you put 'G1ConcRSHotCardLimit', but it doesnt work anymore.

**Comment by Mukul1127** [comment]
Weird, It seems that my jdk 21 install didn't warn me. Fixing
