### ISSUE TITLE
fuck you cuz you call my repo "fake", bitch

### ISSUE THREAD

**Issue by opaa334** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#21]
title XDD

**Comment by opaa334** [comment]
![11 (1)](https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/assets/173428707/d7aec363-db51-4ec3-b83f-fb9df1367126)

**Comment by opaa334** [comment]
finlandic doomer. r/2nordic4you

**Comment by Mukul1127** [comment]
it is tho and you also posted porn
