### ISSUE TITLE
more optimize tips? for azul zulu prime and Transparent HugePage(THP)

### ISSUE THREAD

**Issue by leonpano2006** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#23]
first is that possible to have some test results for Azul zulu prime(for me at least on jave8 is huge improvement compare to regular java)
and for largepage section to have THP?

**Comment by leonpano2006** [comment]
for THP tutorial can fellow this
https://docs.azul.com/prime/Enable-Huge-Pages
should work for zulu prime and regular openjdk(just for prime when system have THP enabled then flag to enable THP is not needed)
is suggested to use 5.4 or newer linux kernel(meself suggest latest LTS(for now is 6.6.y) or latest stable kernel)

**Comment by Mukul1127** [comment]
THP guide added in https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/commit/fba8bf4c89bc4dccf4eb36e62a216460b7eea071, for the testing part, I don't really do any testing as said in the repo and I don't plan to. Feel free to test yourself and maybe even post your results.

**Comment by Mukul1127** [comment]
Also this may be helpful in trying out Azul Platform prime: https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks/issues/49#issuecomment-1716138313
