### ISSUE TITLE
problem about ”nogui“

### ISSUE THREAD

**Issue by RAURORA2** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#25]
I found that many JVM parameters will add "nogui" at the end to improve performance, such as "java -jar xxx.jar nogui". This point was not mentioned in the article. Is there any concern?

**Comment by Mukul1127** [comment]
This is only for the server, it disables the built-in gui for monitoring

**Comment by Mukul1127** [comment]
There is no performance increase

**Comment by RAURORA2** [comment]
> There is no performance increase

For the server, has the performance not improved either? I think it can be reminded.

**Comment by Mukul1127** [comment]
> > There is no performance increase
> 
> For the server, has the performance not improved either? I think it can be reminded.

The nogui option only disables the gui, there is no performance optimization, it's not included in the guide since it's a option for minecraft, not java. Hence it's after the jar file.
