### ISSUE TITLE
Troubles with GraalVM EE Java 8 arguments

### ISSUE THREAD

**Issue by 67aethyl** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#27]
when i put these arguments forge mod loader stucks on model loader, ive tested compatability  of arguments in prism launcher and getting failure: The specified Java binary didn't work with the arguments you provided, ive tested these with and without gc but always get fail. (sorry for bad eng :D)

**Comment by Mukul1127** [comment]
Are you using GraalVM downloaded from here: https://www.oracle.com/downloads/graalvm-downloads.html and selecting java version 8 on 21.X. It sounds like you are using a normal jdk which will not work with the GraalVM arguments.

**Comment by Mukul1127** [comment]
Run `java -version` in a terminal and post the output here.

**Comment by 67aethyl** [comment]
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 1.8.0_421-09)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 21.3.11 (build 25.421-b09-jvmci-21.3-b64, mixed mode)

correct path & home variables.

**Comment by Mukul1127** [comment]
Huh, it should be working, paste your arguments here.

**Comment by Mukul1127** [comment]
Actually make sure your launcher is using that java, the default minecraft launcher uses it's own packaged java 21 by default which older forge does not support I believe

**Comment by 67aethyl** [comment]
-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:AllocatePrefetchStyle=1 -XX:ThreadPriorityPolicy=1 -XX:+UseDynamicNumberOfGCThreads -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=350M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseFPUForSpilling -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.DetectInvertedLoopsAsCounted=true -Dgraal.LoopInversion=true -Dgraal.VectorizeHashes=true -Dgraal.EnterprisePartialUnroll=true -Dgraal.VectorizeSIMD=true -Dgraal.StripMineNonCountedLoops=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.InfeasiblePathCorrelation=true -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:GCTimeRatio=99 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:G1ConcRSHotCardLimit=16

**Comment by 67aethyl** [comment]
yea,launcher using right java

**Comment by 67aethyl** [comment]
I guess this is a problem at the system level or incompatibility with mods, the second is unlikely because forge does not run even without mods.

**Comment by Mukul1127** [comment]
> I guess this is a problem at the system level or incompatibility with mods, the second is unlikely because forge does not run even without mods.

The flags look fine, try running forge with that jre without any java flags or mods and see if it works

**Comment by Mukul1127** [comment]
Going to close this issue though as it seems to be a system issue.
