### ISSUE TITLE
GraalVM failure (windows)

### ISSUE THREAD

**Issue by YnwLNE** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#28]
![image](https://github.com/user-attachments/assets/05e71e10-1372-43b0-bb8e-450c121c0207)

Arguments used 

`-Xmx8G -Xms8G -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:GCTimeRatio=99 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1`

GraalVM 21 and Adoptium 21

**Comment by Mukul1127** [comment]
What do you mean by "GraalVM 21 and Adoptium 21"??? It's impossible to use both at the same time as they are both JREs, by the problem, it seems you used Adoptium 21 while trying to use GraalVM flags, GraalVM flags only work on GraalVM. Use the regular flags for Adoptium.

**Comment by YnwLNE** [comment]
I was using adoptium but switched to GraalVM. I found out it was something to do with the client GC arguments, the GraalVM ones work. Mb for not clarifying, it was early in the morning lol
