### ISSUE TITLE
GraalVM 17 flags for 1.20.1 modded server (Prominence II)

### ISSUE THREAD

**Issue by PilaScat** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#29]
Tried to use the flags but I cannot run the server (I use pterodactyl with this image ghcr.io/rikodev/pterodactyl-graalvm:17)
Now I'm running only with xms 16G and xmx 16G, and it works, but I wanted to optimize the server, 10 player, 400+ mods, 128gb ram, i7-11700k
The flags have an order, I don't know how to handle them, if you could help me, thanks

**Comment by Mukul1127** [comment]
Sorry for not seeing this issue, what do you mean it doesn't run? Is there any error?

**Comment by Mukul1127** [comment]
Start with memory allocation, then base flags, then gc flags, and finally anything else.

**Comment by PilaScat** [comment]
I tried but all other than xms and xmx cant get the server to start, and it's unstable even with only them

**Comment by PilaScat** [comment]
If you could help me with some flags to start, i tried but I cannot combine with GC

**Comment by Mukul1127** [comment]
What do you mean "combine with GC", you just paste the gc flags after the base flags with a space between them.

**Comment by Mukul1127** [comment]
Try these flags: 
```
-Xms12G -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -XX:+UseZGC -XX:AllocatePrefetchStyle=1 -XX:-ZProactive -XX:ConcGCThreads=8
```

 - 12G Ram
 - Uses GraalVM Flags
 - Non-Proactive ZGC
 - 8 Threads for GC

Using 12G of memory as allocating too much memory can cause similar issues and I think 12G should be fine for 10 players. Bump it up if needed

**Comment by PilaScat** [comment]
Seems working for now, will see

**Comment by Mukul1127** [comment]
Awesome! Probably forgot the space between each flag section and put too much ram

**Comment by PilaScat** [comment]
Still lags/freeze sometimes for a few seconds, added 2gigs, now will see

**Comment by Mukul1127** [comment]
Lagging and freezing can indicate too much ram as well though

**Comment by Mukul1127** [comment]
Closing as it seems to be resolved
