### ISSUE TITLE
etUpdatingPauseTimePercent not recognized

### ISSUE THREAD

**Issue by PlayfulPiano** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#4]
Tried "Get" thinking that might've been the right spelling here as well, both failed
![image](https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/assets/3158887/029ac1a0-f81f-4e6a-8511-40cbe4b69375)

**Comment by PlayfulPiano** [comment]
figured it out, meant to be G1RSetUpdatingPauseTimePercent, but it's spelled the title of this issue within the base java flags

**Comment by Mukul1127** [comment]
`GetUpdatingPauseTimePercent=0` doesn't exist anywhere in the readme

**Comment by PlayfulPiano** [comment]
it's meant to be "G1RSetUpdatingPauseTimePercent", you had it as "etUpdatingPauseTimePercent", part of your base benchmarks here:
![image](https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks/assets/3158887/d40694a8-0bcd-47c4-9497-151376d5de66)
