### ISSUE TITLE
GraalVM 21 flags?

### ISSUE THREAD

**Issue by mateus3c** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#6]
I'm confused if the GraalVM 21 flags posted here are meant to be used or not due to " -XX:+DONTCOPYTHESEFLAGS ", could you please explain it to me?

**Comment by Mukul1127** [comment]
>  -XX:+DONTCOPYTHESEFLAGS
Don't copy them, use the tldr to make your own flags
