### ISSUE TITLE
Adoptium 17, Unrecognized VM option 'Use'

### ISSUE THREAD

**Issue by user77yes** [Mukul1127/Minecraft-Performance-Flags-Benchmarks#8]
Hello, I am trying to use the recommended java arguments with Adoptium Temurin 17.0.10+7 LTS, I can't get it to start:    

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+AlwaysActAsServerClassMachine, -XX:+AlwaysPreTouch, -XX:+DisableExplicitGC, -XX:+Use, -XX:NmethodSweepActivity=1, -XX:ReservedCodeCacheSize=400M, -XX:NonNMethodCodeHeapSize=12M, -XX:ProfiledCodeHeapSize=194M, -XX:NonProfiledCodeHeapSize=194M, -XX:-DontCompileHugeMethods, -XX:MaxNodeLimit=240000, -XX:NodeLimitFudgeFactor=8000, -XX:+UseVectorCmov, -XX:+PerfDisableSharedMem, -XX:+UseFastUnorderedTimeStamps, -XX:+UseCriticalJavaThreadPriority, -XX:ThreadPriorityPolicy=1, -XX:AllocatePrefetchStyle=3, -XX:+UseG1GC, -XX:MaxGCPauseMillis=37, -XX:+PerfDisableSharedMem, -XX:G1HeapRegionSize=16M, -XX:G1NewSizePercent=23, -XX:G1ReservePercent=20, -XX:SurvivorRatio=32, -XX:G1MixedGCCountTarget=3, -XX:G1HeapWastePercent=20, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1RSetUpdatingPauseTimePercent=0, -XX:MaxTenuringThreshold=1, -XX:G1SATBBufferEnqueueingThresholdPercent=30, -XX:G1ConcMarkStepDurationMillis=5.0, -XX:G1ConcRefinementServiceIntervalMillis=150, -XX:GCTimeRatio=99, -XX:G1ConcRSHotCardLimit=16, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2730m, -Xmx2730m, -Duser.language=en]

Minecraft process ID: 4856

Unrecognized VM option 'Use'

(using the base flags for Java 11+, and those of the G1GC collector for the client side)

Maybe I'm doing something wrong? In their respective cases I used the ones for GraalVM 17 and 8, and for java 8 (Adoptium), those worked fine.

**Comment by user77yes** [comment]
It works by just taking out the 'Use' option. Anyway, that's to specify the garbage collector right there, isn't it? 
Now it starts, although it says that my hardware doesn't support INVTSC, maybe because my cpu is old

**Comment by couleurm** [comment]
Had the same issue, removing the arg made it work, was it inserted by mistake?

**Comment by Mukul1127** [comment]
Thanks, this is a mistake
